---
- name: Update Logstash server IP address in Filebeat configuration
  hosts: filebeat
  become: yes
  vars:
    logstash_ip: "{{ logstash_server_ip }}"  # Переменная для нового IP-адреса Logstash
  tasks:
    - name: Ensure Filebeat is installed
      apt:
        name: filebeat
        state: present
      when: ansible_os_family == "Debian"

    - name: Backup Filebeat configuration
      copy:
        src: /etc/filebeat/filebeat.yml
        dest: /etc/filebeat/filebeat.yml.bak
        remote_src: yes
      tags: backup

    - name: Update Logstash server IP address in Filebeat configuration
      blockinfile:
        path: /etc/filebeat/filebeat.yml
        block: |
          output.logstash:
            hosts: ["{{ logstash_ip }}"]
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Logstash Configuration"
        insertafter: "^output\\.logstash:$"
      notify: Restart Filebeat

    - name: Validate Filebeat configuration
      command: filebeat test config
      register: config_test
      failed_when: config_test.rc != 0

    - name: Ensure Filebeat service is running
      service:
        name: filebeat
        state: started
        enabled: yes

  handlers:
    - name: Restart Filebeat
      service:
        name: filebeat
        state: restarted