export const attackScripts = [
  {
    id: 1,
    nameKey: 'attack_script_1_name',
    descriptionKey: 'attack_script_1_description',
    fullDescriptionKey: 'attack_script_1_full_description',
    imageKey: './assets/attacks/smtp.png',
    backendRoute: '/attacks/opensmtpd-exploit',
  },
  {
    id: 2,
    nameKey: 'attack_script_2_name',
    descriptionKey: 'attack_script_2_description',
    fullDescriptionKey: 'attack_script_2_full_description',
    imageKey: './assets/attacks/nmap.png',
    backendRoute: '/attacks/nmap-scan',
  },
  {
    id: 3,
    nameKey: 'attack_script_3_name',
    descriptionKey: 'attack_script_3_description',
    fullDescriptionKey: 'attack_script_3_full_description',
    imageKey: './assets/attacks/ftp.jpeg',
    backendRoute: '/attacks/vsftpd-msf-exploit',
  },
  {
    id: 4,
    nameKey: 'attack_script_4_name',
    descriptionKey: 'attack_script_4_description',
    fullDescriptionKey: 'attack_script_4_full_description',
    imageKey: './assets/attacks/sqli.png',
    backendRoute: '/attacks/juice-shop-login-sqli',
  },
  {
    id: 5,
    nameKey: 'attack_script_5_name',
    descriptionKey: 'attack_script_5_description',
    fullDescriptionKey: 'attack_script_5_full_description',
    imageKey: './assets/attacks/dirb.jpeg',
    backendRoute: '/attacks/dirb',
  },
  {
    id: 6,
    nameKey: 'attack_script_6_name',
    descriptionKey: 'attack_script_6_description',
    fullDescriptionKey: 'attack_script_6_full_description',
    imageKey: './assets/attacks/mikrotik.png',
    backendRoute: '/attacks/mikrotik-msf-exploit',
  },
];